C#에서는 예외상황이 발생하면 스스로 에러 메세지를 발생한 후, 프로그램이 죽어버린다

하지만. 유니티는 Start문에서 예외가 발생하면 더이상 Start문을 실행하지 않고 업데이트로 넘어가고

Update에서 예외가 발생하면 Update문의 예외 아래 실행문은 실행하지 않고 다음 Update문으로

넘어간다.

하지만 예외처리를 사용하여 예외를 처리할 수 있다.

### 예외(Exception)?

예외는 프로그램 실행 도중 발생하는 예상치 못한 오류나 비정상적인 상황을 의미한다

C#에서는 다양한 내장 예외 클래스(`NullReferenceException`, `ArgumentException` 등)가 있으며

필요에 따라 사용자 정의 예외를 만들 수 있다

### 언제 사용해야하나

예외 처리는 예외적인 상황 즉 정상적인 실행 흐름에서 발생해서는 안되는 문제를다룰 때

사용한다. 아래와 같은 경우가 대표적이다

- **파일 입출력:** 파일이 존재하지 않거나 접근 권한이 없는 경우
- **네트워크 통신:** 연결 실패, 타임아웃, 데이터 수신 오류등의 경우
- **외부 리소스 접근:** 데이터베이스 연결 실패, API 호출 오류등의 경우
- **불가피한 런타임 오류:** 계산과정에서 0으로 나누는 등의 경우

### try catch

try catch문은 예외를 찾고, 그 예외가 발생할 경우 실행할 문을 넣는 기법이다.

try에 실행할 코드를, catch에 예외가 발생했을때 실행할 실행문을 넣으면 된다.

아래는 try catch문의 예시이다.

```csharp
using UnityEngine;
using System;

public class Example : MonoBehaviour
{
		GameObject a;
		
		private void Start()
		{
				//a = new GameObject();
				//a를 할당하지 않았음
				
				try
				{
						Debug.Log(a.name);//a가 할당되어있지 않기 때문에 예외가 발생하게 된다.
				}
				catch
				}
						Debug.Log("Error");
				}
				Debug.Log("아래도 실행됨");
		}
}
```

### try finally

try finally문은 예외를 찾고, 그 예외가 발생하더라도 Finally문이 실행되는 기법이다.

try문에 실행할 코드를 넣고, finally문에는 반드시 실행되어야 하는 실행문을 넣는다.

아래는 try finally문의 예시이다.

```csharp
using UnityEngine;
using System;

public class Example2 : MonoBehaviour
{
		GameObject b;
		//b를 할당하지 않음
		
		void Start()
		{
				//b = new GameObject;
				//b를 할당하지 않음
				
				try
				{
						Debug.Log(b.name);
				}
				finally
				{
						Debug.Log("이 부분은 무조건 실행");
				}
				
				Debug.Log("여기는 실행되지 않음");
		}
		
```

### try catch finally

try catch finally문은 앞서 설명한 try catch와 try finally를 섞어서 사용한다.

아래는 try catch finally문의 예시이다.

```csharp
using UnityEngine;
using System;

public class Example3 : MonoBehaviour
{
		GameObject c;
		//c를 할당하지 않음
		
		void Start()
		{
				//C = new GameObject;
				//b를 할당하지 않음
				
				try
				{
						Debug.Log(c.name);
				}
				catch
				{
						Debug.Log("여기 실행");
				{
				finally
				{
						Debug.Log("여기도 실행");
				}
				
				Debug.Log("여기도 실행");
		}
		
```

### throw

throw문은 new 키워드를 활용해 특정 예외 클래스의 인스턴스를 생성, 그 인스턴스를 throw하여

호출자에게 예외 상황을 알리는 역할을 한다.

아래는 throw문의 예시이다

```csharp
using UnityEngine;
using System;

public class Example4 : MonoBehaviour
{
		void Start()
		{
				throw new Exception("임의로 만든 예외입니다");
		}
}
```

### 장점

1. 오류 전파 및 캡슐화
    - 오류가 발생한 위치와 상관없이, 예외를 호출자에게 전파하여 한곳에서 일괄적으로 처리할 수 있다.
    - 오류 상황을 캡슐화 하여 코드의 가독성과 유지보수를 높인다.
2. 비정상적 상황에 대한 명확한 의사 전달
    - 예외 메세지와 스택 트레이스를 통해 어떤 오류가 발생했는지 정확히 파악 가능.
3. 코드의 단순화
    - 여러 단계의 리턴 값 검사를 if문으로 처리하는 대신, 예외 처리 구문을 사용해 코드를 간결하게 유지할 수 있다.

### 단점

1. **성능 오버헤드**
    - 예외 발생 및 처리 과정은 일반적인 조건문 체크보다 성능 비용이 크다. 그러기에 정상적인 흐름에서 자주 발생해선 안된다
2. **남용시 코드 복잡성 증가**
    - 예외를 정상적인 제어 흐름으로 남용하면 코드가 복잡해지고, 실제 오류와 구분하기 어려워진다.
3. **예외 상황의 숨김 위험**
    - catch 블록에서 예외를 단순히 무시하거나 잘못 처리하면, 문제가 발생한 원인을 파악하기 어려워지고 디버깅이 힘들어집니다.

### 결론

예외처리는 **비정상적인, 예외적인 상황**에 효과적으로 대응하는 강력한 도구이다

하지만, 정상적인 제어 흐름에선 **if문등의 간단한 조건문**을 사용해 처리하는 것이 바람직하며

예외는 **정말 예외적인 상황**에서 사용하는 것이 좋다.